name: menhir
on: [push, pull_request]
jobs:
  menhir:
    name: Check Menhir version
    steps:
      - name: Check Menhir version
        shell: bash
        run: |
          grep --count --max-count=1 --quiet 'MenhirLib.StaticVersion.require_30210419' boot/menhir/parser.ml
